seeder:
  file: ./seeder/seeder.rb
  disabled: false

parsers:
  - file: ./parsers/listings.rb
    disabled: false
    page_type: listings
  
  - file: ./parsers/products.rb
    page_type: products
    disabled: false